services:
  api:
    container_name: forum-api
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: bun run start:dev
    networks:
      - forum.test

networks:
  forum.test:
    name: forum.test
    external: true
