services:
  api:
    container_name: forum-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - forum.test

networks:
  forum.test:
    name: forum.test
    external: true
