import type { OccupationTitle } from './occupation-key'

/**
 * Vendored occupation title corpus for typeahead (not seeded into tags).
 * Existing product keys (founder, ceo, …) are preserved.
 */
export const OCCUPATION_TITLES: OccupationTitle[] = [
  { key: '3d_designer', name: '3D Designer' },
  { key: 'accelerator_manager', name: 'Accelerator Manager' },
  { key: 'accessibility_specialist', name: 'Accessibility Specialist' },
  { key: 'account_executive', name: 'Account Executive' },
  { key: 'account_manager', name: 'Account Manager' },
  { key: 'accountant', name: 'Accountant' },
  { key: 'actuary', name: 'Actuary' },
  { key: 'ads_analyst', name: 'Ads Analyst' },
  { key: 'ads_architect', name: 'Ads Architect' },
  { key: 'ads_consultant', name: 'Ads Consultant' },
  { key: 'ads_designer', name: 'Ads Designer' },
  { key: 'ads_director', name: 'Ads Director' },
  { key: 'ads_engineer', name: 'Ads Engineer' },
  { key: 'ads_lead', name: 'Ads Lead' },
  { key: 'ads_manager', name: 'Ads Manager' },
  { key: 'ads_marketer', name: 'Ads Marketer' },
  { key: 'ads_operator', name: 'Ads Operator' },
  { key: 'ads_product_manager', name: 'Ads Product Manager' },
  { key: 'ads_researcher', name: 'Ads Researcher' },
  { key: 'ads_sales_lead', name: 'Ads Sales Lead' },
  { key: 'ads_scientist', name: 'Ads Scientist' },
  { key: 'ads_specialist', name: 'Ads Specialist' },
  { key: 'advisor', name: 'Advisor' },
  { key: 'aerospace_analyst', name: 'Aerospace Analyst' },
  { key: 'aerospace_architect', name: 'Aerospace Architect' },
  { key: 'aerospace_consultant', name: 'Aerospace Consultant' },
  { key: 'aerospace_designer', name: 'Aerospace Designer' },
  { key: 'aerospace_director', name: 'Aerospace Director' },
  { key: 'aerospace_engineer', name: 'Aerospace Engineer' },
  { key: 'aerospace_lead', name: 'Aerospace Lead' },
  { key: 'aerospace_manager', name: 'Aerospace Manager' },
  { key: 'aerospace_marketer', name: 'Aerospace Marketer' },
  { key: 'aerospace_operator', name: 'Aerospace Operator' },
  { key: 'aerospace_product_manager', name: 'Aerospace Product Manager' },
  { key: 'aerospace_researcher', name: 'Aerospace Researcher' },
  { key: 'aerospace_sales_lead', name: 'Aerospace Sales Lead' },
  { key: 'aerospace_scientist', name: 'Aerospace Scientist' },
  { key: 'aerospace_specialist', name: 'Aerospace Specialist' },
  { key: 'affiliate_manager', name: 'Affiliate Manager' },
  { key: 'agile_coach', name: 'Agile Coach' },
  { key: 'agriculture_analyst', name: 'Agriculture Analyst' },
  { key: 'agriculture_architect', name: 'Agriculture Architect' },
  { key: 'agriculture_consultant', name: 'Agriculture Consultant' },
  { key: 'agriculture_designer', name: 'Agriculture Designer' },
  { key: 'agriculture_director', name: 'Agriculture Director' },
  { key: 'agriculture_engineer', name: 'Agriculture Engineer' },
  { key: 'agriculture_lead', name: 'Agriculture Lead' },
  { key: 'agriculture_manager', name: 'Agriculture Manager' },
  { key: 'agriculture_marketer', name: 'Agriculture Marketer' },
  { key: 'agriculture_operator', name: 'Agriculture Operator' },
  { key: 'agriculture_product_manager', name: 'Agriculture Product Manager' },
  { key: 'agriculture_researcher', name: 'Agriculture Researcher' },
  { key: 'agriculture_sales_lead', name: 'Agriculture Sales Lead' },
  { key: 'agriculture_scientist', name: 'Agriculture Scientist' },
  { key: 'agriculture_specialist', name: 'Agriculture Specialist' },
  { key: 'ai_analyst', name: 'AI Analyst' },
  { key: 'ai_architect', name: 'AI Architect' },
  { key: 'ai_consultant', name: 'AI Consultant' },
  { key: 'ai_designer', name: 'AI Designer' },
  { key: 'ai_director', name: 'AI Director' },
  { key: 'ai_engineer', name: 'AI Engineer' },
  { key: 'ai_lead', name: 'AI Lead' },
  { key: 'ai_manager', name: 'AI Manager' },
  { key: 'ai_marketer', name: 'AI Marketer' },
  { key: 'ai_operator', name: 'AI Operator' },
  { key: 'ai_product_manager', name: 'AI Product Manager' },
  { key: 'ai_researcher', name: 'AI Researcher' },
  { key: 'ai_sales_lead', name: 'AI Sales Lead' },
  { key: 'ai_scientist', name: 'AI Scientist' },
  { key: 'ai_specialist', name: 'AI Specialist' },
  { key: 'analytics_analyst', name: 'Analytics Analyst' },
  { key: 'analytics_architect', name: 'Analytics Architect' },
  { key: 'analytics_consultant', name: 'Analytics Consultant' },
  { key: 'analytics_designer', name: 'Analytics Designer' },
  { key: 'analytics_director', name: 'Analytics Director' },
  { key: 'analytics_engineer', name: 'Analytics Engineer' },
  { key: 'analytics_lead', name: 'Analytics Lead' },
  { key: 'analytics_manager', name: 'Analytics Manager' },
  { key: 'analytics_marketer', name: 'Analytics Marketer' },
  { key: 'analytics_operator', name: 'Analytics Operator' },
  { key: 'analytics_product_manager', name: 'Analytics Product Manager' },
  { key: 'analytics_researcher', name: 'Analytics Researcher' },
  { key: 'analytics_sales_lead', name: 'Analytics Sales Lead' },
  { key: 'analytics_scientist', name: 'Analytics Scientist' },
  { key: 'analytics_specialist', name: 'Analytics Specialist' },
  { key: 'android_engineer', name: 'Android Engineer' },
  { key: 'angel_investor', name: 'Angel investor' },
  { key: 'animator', name: 'Animator' },
  { key: 'api_engineer', name: 'API Engineer' },
  { key: 'applied_scientist', name: 'Applied Scientist' },
  { key: 'ar_vr_engineer', name: 'AR/VR Engineer' },
  { key: 'architect', name: 'Architect' },
  { key: 'art_director', name: 'Art Director' },
  { key: 'assistant_professor', name: 'Assistant Professor' },
  { key: 'associate_account_executive', name: 'Associate Account Executive' },
  { key: 'associate_backend_engineer', name: 'Associate Backend Engineer' },
  { key: 'associate_business_analyst', name: 'Associate Business Analyst' },
  { key: 'associate_consultant', name: 'Associate Consultant' },
  { key: 'associate_content_writer', name: 'Associate Content Writer' },
  { key: 'associate_data_analyst', name: 'Associate Data Analyst' },
  { key: 'associate_data_engineer', name: 'Associate Data Engineer' },
  { key: 'associate_data_scientist', name: 'Associate Data Scientist' },
  { key: 'associate_designer', name: 'Associate Designer' },
  { key: 'associate_devops_engineer', name: 'Associate DevOps Engineer' },
  { key: 'associate_finance_manager', name: 'Associate Finance Manager' },
  { key: 'associate_frontend_engineer', name: 'Associate Frontend Engineer' },
  { key: 'associate_fullstack_engineer', name: 'Associate Fullstack Engineer' },
  { key: 'associate_growth_manager', name: 'Associate Growth Manager' },
  { key: 'associate_marketing_manager', name: 'Associate Marketing Manager' },
  { key: 'associate_ml_engineer', name: 'Associate ML Engineer' },
  { key: 'associate_mobile_engineer', name: 'Associate Mobile Engineer' },
  { key: 'associate_operations_manager', name: 'Associate Operations Manager' },
  { key: 'associate_product_designer', name: 'Associate Product Designer' },
  { key: 'associate_product_manager', name: 'Associate Product Manager' },
  { key: 'associate_professor', name: 'Associate Professor' },
  { key: 'associate_program_manager', name: 'Associate Program Manager' },
  { key: 'associate_project_manager', name: 'Associate Project Manager' },
  { key: 'associate_qa_engineer', name: 'Associate QA Engineer' },
  { key: 'associate_recruiter', name: 'Associate Recruiter' },
  { key: 'associate_researcher', name: 'Associate Researcher' },
  { key: 'associate_sales_manager', name: 'Associate Sales Manager' },
  { key: 'associate_security_engineer', name: 'Associate Security Engineer' },
  { key: 'associate_software_engineer', name: 'Associate Software Engineer' },
  { key: 'associate_strategy_manager', name: 'Associate Strategy Manager' },
  { key: 'associate_ux_designer', name: 'Associate UX Designer' },
  { key: 'athlete', name: 'Athlete' },
  { key: 'attorney', name: 'Attorney' },
  { key: 'automation_engineer', name: 'Automation Engineer' },
  { key: 'automation_specialist', name: 'Automation Specialist' },
  { key: 'automotive_analyst', name: 'Automotive Analyst' },
  { key: 'automotive_architect', name: 'Automotive Architect' },
  { key: 'automotive_consultant', name: 'Automotive Consultant' },
  { key: 'automotive_designer', name: 'Automotive Designer' },
  { key: 'automotive_director', name: 'Automotive Director' },
  { key: 'automotive_engineer', name: 'Automotive Engineer' },
  { key: 'automotive_lead', name: 'Automotive Lead' },
  { key: 'automotive_manager', name: 'Automotive Manager' },
  { key: 'automotive_marketer', name: 'Automotive Marketer' },
  { key: 'automotive_operator', name: 'Automotive Operator' },
  { key: 'automotive_product_manager', name: 'Automotive Product Manager' },
  { key: 'automotive_researcher', name: 'Automotive Researcher' },
  { key: 'automotive_sales_lead', name: 'Automotive Sales Lead' },
  { key: 'automotive_scientist', name: 'Automotive Scientist' },
  { key: 'automotive_specialist', name: 'Automotive Specialist' },
  { key: 'b2b_analyst', name: 'B2B Analyst' },
  { key: 'b2b_architect', name: 'B2B Architect' },
  { key: 'b2b_consultant', name: 'B2B Consultant' },
  { key: 'b2b_designer', name: 'B2B Designer' },
  { key: 'b2b_director', name: 'B2B Director' },
  { key: 'b2b_engineer', name: 'B2B Engineer' },
  { key: 'b2b_lead', name: 'B2B Lead' },
  { key: 'b2b_manager', name: 'B2B Manager' },
  { key: 'b2b_marketer', name: 'B2B Marketer' },
  { key: 'b2b_operator', name: 'B2B Operator' },
  { key: 'b2b_product_manager', name: 'B2B Product Manager' },
  { key: 'b2b_researcher', name: 'B2B Researcher' },
  { key: 'b2b_sales_lead', name: 'B2B Sales Lead' },
  { key: 'b2b_scientist', name: 'B2B Scientist' },
  { key: 'b2b_specialist', name: 'B2B Specialist' },
  { key: 'b2c_analyst', name: 'B2C Analyst' },
  { key: 'b2c_architect', name: 'B2C Architect' },
  { key: 'b2c_consultant', name: 'B2C Consultant' },
  { key: 'b2c_designer', name: 'B2C Designer' },
  { key: 'b2c_director', name: 'B2C Director' },
  { key: 'b2c_engineer', name: 'B2C Engineer' },
  { key: 'b2c_lead', name: 'B2C Lead' },
  { key: 'b2c_manager', name: 'B2C Manager' },
  { key: 'b2c_marketer', name: 'B2C Marketer' },
  { key: 'b2c_operator', name: 'B2C Operator' },
  { key: 'b2c_product_manager', name: 'B2C Product Manager' },
  { key: 'b2c_researcher', name: 'B2C Researcher' },
  { key: 'b2c_sales_lead', name: 'B2C Sales Lead' },
  { key: 'b2c_scientist', name: 'B2C Scientist' },
  { key: 'b2c_specialist', name: 'B2C Specialist' },
  { key: 'backend_engineer', name: 'Backend Engineer' },
  { key: 'banker', name: 'Banker' },
  { key: 'banking_analyst', name: 'Banking Analyst' },
  { key: 'banking_architect', name: 'Banking Architect' },
  { key: 'banking_consultant', name: 'Banking Consultant' },
  { key: 'banking_designer', name: 'Banking Designer' },
  { key: 'banking_director', name: 'Banking Director' },
  { key: 'banking_engineer', name: 'Banking Engineer' },
  { key: 'banking_lead', name: 'Banking Lead' },
  { key: 'banking_manager', name: 'Banking Manager' },
  { key: 'banking_marketer', name: 'Banking Marketer' },
  { key: 'banking_operator', name: 'Banking Operator' },
  { key: 'banking_product_manager', name: 'Banking Product Manager' },
  { key: 'banking_researcher', name: 'Banking Researcher' },
  { key: 'banking_sales_lead', name: 'Banking Sales Lead' },
  { key: 'banking_scientist', name: 'Banking Scientist' },
  { key: 'banking_specialist', name: 'Banking Specialist' },
  { key: 'barista', name: 'Barista' },
  { key: 'between_roles', name: 'Between Roles' },
  { key: 'bi_analyst', name: 'BI Analyst' },
  { key: 'bi_developer', name: 'BI Developer' },
  { key: 'biomedical_engineer', name: 'Biomedical Engineer' },
  { key: 'biotech_analyst', name: 'Biotech Analyst' },
  { key: 'biotech_architect', name: 'Biotech Architect' },
  { key: 'biotech_consultant', name: 'Biotech Consultant' },
  { key: 'biotech_designer', name: 'Biotech Designer' },
  { key: 'biotech_director', name: 'Biotech Director' },
  { key: 'biotech_engineer', name: 'Biotech Engineer' },
  { key: 'biotech_lead', name: 'Biotech Lead' },
  { key: 'biotech_manager', name: 'Biotech Manager' },
  { key: 'biotech_marketer', name: 'Biotech Marketer' },
  { key: 'biotech_operator', name: 'Biotech Operator' },
  { key: 'biotech_product_manager', name: 'Biotech Product Manager' },
  { key: 'biotech_researcher', name: 'Biotech Researcher' },
  { key: 'biotech_sales_lead', name: 'Biotech Sales Lead' },
  { key: 'biotech_scientist', name: 'Biotech Scientist' },
  { key: 'biotech_specialist', name: 'Biotech Specialist' },
  { key: 'blockchain_engineer', name: 'Blockchain Engineer' },
  { key: 'board_member', name: 'Board Member' },
  { key: 'bookkeeper', name: 'Bookkeeper' },
  { key: 'brand_designer', name: 'Brand Designer' },
  { key: 'brand_manager', name: 'Brand Manager' },
  { key: 'build_engineer', name: 'Build Engineer' },
  { key: 'business_analyst', name: 'Business Analyst' },
  { key: 'business_development_manager', name: 'Business Development Manager' },
  { key: 'business_operations_manager', name: 'Business Operations Manager' },
  { key: 'cao', name: 'CAO' },
  { key: 'career_break', name: 'Career Break' },
  { key: 'ceo', name: 'CEO' },
  { key: 'cfo', name: 'CFO' },
  { key: 'channel_partner_manager', name: 'Channel Partner Manager' },
  { key: 'chef', name: 'Chef' },
  { key: 'chemical_engineer', name: 'Chemical Engineer' },
  { key: 'chief_ai_officer', name: 'Chief AI Officer' },
  { key: 'chief_data_officer', name: 'Chief Data Officer' },
  { key: 'chief_of_staff', name: 'Chief of Staff' },
  { key: 'chief_product_officer', name: 'Chief Product Officer' },
  { key: 'chief_technology_officer', name: 'Chief Technology Officer' },
  { key: 'chro', name: 'CHRO' },
  { key: 'cio', name: 'CIO' },
  { key: 'ciso', name: 'CISO' },
  { key: 'civil_engineer', name: 'Civil Engineer' },
  { key: 'civil_servant', name: 'Civil Servant' },
  { key: 'client_partner', name: 'Client Partner' },
  { key: 'climate_analyst', name: 'Climate Analyst' },
  { key: 'climate_architect', name: 'Climate Architect' },
  { key: 'climate_consultant', name: 'Climate Consultant' },
  { key: 'climate_designer', name: 'Climate Designer' },
  { key: 'climate_director', name: 'Climate Director' },
  { key: 'climate_engineer', name: 'Climate Engineer' },
  { key: 'climate_lead', name: 'Climate Lead' },
  { key: 'climate_manager', name: 'Climate Manager' },
  { key: 'climate_marketer', name: 'Climate Marketer' },
  { key: 'climate_operator', name: 'Climate Operator' },
  { key: 'climate_product_manager', name: 'Climate Product Manager' },
  { key: 'climate_researcher', name: 'Climate Researcher' },
  { key: 'climate_sales_lead', name: 'Climate Sales Lead' },
  { key: 'climate_scientist', name: 'Climate Scientist' },
  { key: 'climate_specialist', name: 'Climate Specialist' },
  { key: 'cloud_analyst', name: 'Cloud Analyst' },
  { key: 'cloud_architect', name: 'Cloud Architect' },
  { key: 'cloud_consultant', name: 'Cloud Consultant' },
  { key: 'cloud_designer', name: 'Cloud Designer' },
  { key: 'cloud_director', name: 'Cloud Director' },
  { key: 'cloud_engineer', name: 'Cloud Engineer' },
  { key: 'cloud_lead', name: 'Cloud Lead' },
  { key: 'cloud_manager', name: 'Cloud Manager' },
  { key: 'cloud_marketer', name: 'Cloud Marketer' },
  { key: 'cloud_operator', name: 'Cloud Operator' },
  { key: 'cloud_product_manager', name: 'Cloud Product Manager' },
  { key: 'cloud_researcher', name: 'Cloud Researcher' },
  { key: 'cloud_sales_lead', name: 'Cloud Sales Lead' },
  { key: 'cloud_scientist', name: 'Cloud Scientist' },
  { key: 'cloud_specialist', name: 'Cloud Specialist' },
  { key: 'cmo', name: 'CMO' },
  { key: 'co_founder', name: 'Co-founder' },
  { key: 'coach', name: 'Coach' },
  { key: 'communications_analyst', name: 'Communications Analyst' },
  { key: 'communications_architect', name: 'Communications Architect' },
  { key: 'communications_consultant', name: 'Communications Consultant' },
  { key: 'communications_designer', name: 'Communications Designer' },
  { key: 'communications_director', name: 'Communications Director' },
  { key: 'communications_engineer', name: 'Communications Engineer' },
  { key: 'communications_lead', name: 'Communications Lead' },
  { key: 'communications_manager', name: 'Communications Manager' },
  { key: 'communications_marketer', name: 'Communications Marketer' },
  { key: 'communications_operator', name: 'Communications Operator' },
  { key: 'communications_researcher', name: 'Communications Researcher' },
  { key: 'communications_sales_lead', name: 'Communications Sales Lead' },
  { key: 'communications_scientist', name: 'Communications Scientist' },
  { key: 'communications_specialist', name: 'Communications Specialist' },
  { key: 'community_lead', name: 'Community Lead' },
  { key: 'community_manager', name: 'Community Manager' },
  { key: 'compliance_manager', name: 'Compliance Manager' },
  { key: 'computer_vision_engineer', name: 'Computer Vision Engineer' },
  { key: 'consultant', name: 'Consultant' },
  { key: 'consumer_analyst', name: 'Consumer Analyst' },
  { key: 'consumer_architect', name: 'Consumer Architect' },
  { key: 'consumer_consultant', name: 'Consumer Consultant' },
  { key: 'consumer_designer', name: 'Consumer Designer' },
  { key: 'consumer_director', name: 'Consumer Director' },
  { key: 'consumer_engineer', name: 'Consumer Engineer' },
  { key: 'consumer_lead', name: 'Consumer Lead' },
  { key: 'consumer_manager', name: 'Consumer Manager' },
  { key: 'consumer_marketer', name: 'Consumer Marketer' },
  { key: 'consumer_operator', name: 'Consumer Operator' },
  { key: 'consumer_product_manager', name: 'Consumer Product Manager' },
  { key: 'consumer_researcher', name: 'Consumer Researcher' },
  { key: 'consumer_sales_lead', name: 'Consumer Sales Lead' },
  { key: 'consumer_scientist', name: 'Consumer Scientist' },
  { key: 'consumer_specialist', name: 'Consumer Specialist' },
  { key: 'content_marketer', name: 'Content Marketer' },
  { key: 'content_moderator', name: 'Content Moderator' },
  { key: 'content_writer', name: 'Content Writer' },
  { key: 'contractor', name: 'Contractor' },
  { key: 'controller', name: 'Controller' },
  { key: 'coo', name: 'COO' },
  { key: 'copywriter', name: 'Copywriter' },
  { key: 'corporate_counsel', name: 'Corporate Counsel' },
  { key: 'corporate_strategy_associate', name: 'Corporate Strategy Associate' },
  { key: 'corporate_venture_capitalist', name: 'Corporate Venture Capitalist' },
  { key: 'cpo', name: 'CPO' },
  { key: 'creative_director', name: 'Creative Director' },
  { key: 'creator', name: 'Creator' },
  { key: 'cro', name: 'CRO' },
  { key: 'crypto_analyst', name: 'Crypto Analyst' },
  { key: 'crypto_architect', name: 'Crypto Architect' },
  { key: 'crypto_consultant', name: 'Crypto Consultant' },
  { key: 'crypto_designer', name: 'Crypto Designer' },
  { key: 'crypto_director', name: 'Crypto Director' },
  { key: 'crypto_engineer', name: 'Crypto Engineer' },
  { key: 'crypto_lead', name: 'Crypto Lead' },
  { key: 'crypto_manager', name: 'Crypto Manager' },
  { key: 'crypto_marketer', name: 'Crypto Marketer' },
  { key: 'crypto_operator', name: 'Crypto Operator' },
  { key: 'crypto_product_manager', name: 'Crypto Product Manager' },
  { key: 'crypto_researcher', name: 'Crypto Researcher' },
  { key: 'crypto_sales_lead', name: 'Crypto Sales Lead' },
  { key: 'crypto_scientist', name: 'Crypto Scientist' },
  { key: 'crypto_specialist', name: 'Crypto Specialist' },
  { key: 'crypto_trader', name: 'Crypto Trader' },
  { key: 'cto', name: 'CTO' },
  { key: 'customer_success_engineer', name: 'Customer Success Engineer' },
  { key: 'customer_success_manager', name: 'Customer Success Manager' },
  { key: 'customer_support_specialist', name: 'Customer Support Specialist' },
  { key: 'cybersecurity_analyst', name: 'Cybersecurity Analyst' },
  { key: 'cybersecurity_architect', name: 'Cybersecurity Architect' },
  { key: 'cybersecurity_consultant', name: 'Cybersecurity Consultant' },
  { key: 'cybersecurity_designer', name: 'Cybersecurity Designer' },
  { key: 'cybersecurity_director', name: 'Cybersecurity Director' },
  { key: 'cybersecurity_engineer', name: 'Cybersecurity Engineer' },
  { key: 'cybersecurity_lead', name: 'Cybersecurity Lead' },
  { key: 'cybersecurity_manager', name: 'Cybersecurity Manager' },
  { key: 'cybersecurity_marketer', name: 'Cybersecurity Marketer' },
  { key: 'cybersecurity_operator', name: 'Cybersecurity Operator' },
  { key: 'cybersecurity_researcher', name: 'Cybersecurity Researcher' },
  { key: 'cybersecurity_sales_lead', name: 'Cybersecurity Sales Lead' },
  { key: 'cybersecurity_scientist', name: 'Cybersecurity Scientist' },
  { key: 'cybersecurity_specialist', name: 'Cybersecurity Specialist' },
  { key: 'data_analyst', name: 'Data Analyst' },
  { key: 'data_engineer', name: 'Data Engineer' },
  { key: 'data_platform_engineer', name: 'Data Platform Engineer' },
  { key: 'data_scientist', name: 'Data Scientist' },
  { key: 'database_administrator', name: 'Database Administrator' },
  { key: 'decision_scientist', name: 'Decision Scientist' },
  { key: 'deep_learning_engineer', name: 'Deep Learning Engineer' },
  { key: 'defense_analyst', name: 'Defense Analyst' },
  { key: 'defense_architect', name: 'Defense Architect' },
  { key: 'defense_consultant', name: 'Defense Consultant' },
  { key: 'defense_designer', name: 'Defense Designer' },
  { key: 'defense_director', name: 'Defense Director' },
  { key: 'defense_engineer', name: 'Defense Engineer' },
  { key: 'defense_lead', name: 'Defense Lead' },
  { key: 'defense_manager', name: 'Defense Manager' },
  { key: 'defense_marketer', name: 'Defense Marketer' },
  { key: 'defense_operator', name: 'Defense Operator' },
  { key: 'defense_product_manager', name: 'Defense Product Manager' },
  { key: 'defense_researcher', name: 'Defense Researcher' },
  { key: 'defense_sales_lead', name: 'Defense Sales Lead' },
  { key: 'defense_scientist', name: 'Defense Scientist' },
  { key: 'defense_specialist', name: 'Defense Specialist' },
  { key: 'demand_generation_manager', name: 'Demand Generation Manager' },
  { key: 'dentist', name: 'Dentist' },
  { key: 'design_manager', name: 'Design Manager' },
  { key: 'design_system_designer', name: 'Design System Designer' },
  { key: 'designer', name: 'Designer' },
  { key: 'designops_manager', name: 'DesignOps Manager' },
  { key: 'developer_advocate', name: 'Developer Advocate' },
  { key: 'developer_relations_manager', name: 'Developer Relations Manager' },
  { key: 'devops_engineer', name: 'DevOps Engineer' },
  { key: 'devtools_analyst', name: 'DevTools Analyst' },
  { key: 'devtools_architect', name: 'DevTools Architect' },
  { key: 'devtools_consultant', name: 'DevTools Consultant' },
  { key: 'devtools_designer', name: 'DevTools Designer' },
  { key: 'devtools_director', name: 'DevTools Director' },
  { key: 'devtools_engineer', name: 'DevTools Engineer' },
  { key: 'devtools_lead', name: 'DevTools Lead' },
  { key: 'devtools_manager', name: 'DevTools Manager' },
  { key: 'devtools_marketer', name: 'DevTools Marketer' },
  { key: 'devtools_operator', name: 'DevTools Operator' },
  { key: 'devtools_product_manager', name: 'DevTools Product Manager' },
  { key: 'devtools_researcher', name: 'DevTools Researcher' },
  { key: 'devtools_sales_lead', name: 'DevTools Sales Lead' },
  { key: 'devtools_scientist', name: 'DevTools Scientist' },
  { key: 'devtools_specialist', name: 'DevTools Specialist' },
  { key: 'digital_marketing_manager', name: 'Digital Marketing Manager' },
  { key: 'diplomat', name: 'Diplomat' },
  { key: 'director_of_engineering', name: 'Director of Engineering' },
  { key: 'director_of_marketing', name: 'Director of Marketing' },
  { key: 'director_of_product', name: 'Director of Product' },
  { key: 'director_of_sales', name: 'Director of Sales' },
  { key: 'driver', name: 'Driver' },
  { key: 'e_commerce_analyst', name: 'E-commerce Analyst' },
  { key: 'e_commerce_architect', name: 'E-commerce Architect' },
  { key: 'e_commerce_consultant', name: 'E-commerce Consultant' },
  { key: 'e_commerce_designer', name: 'E-commerce Designer' },
  { key: 'e_commerce_director', name: 'E-commerce Director' },
  { key: 'e_commerce_engineer', name: 'E-commerce Engineer' },
  { key: 'e_commerce_lead', name: 'E-commerce Lead' },
  { key: 'e_commerce_manager', name: 'E-commerce Manager' },
  { key: 'e_commerce_marketer', name: 'E-commerce Marketer' },
  { key: 'e_commerce_operator', name: 'E-commerce Operator' },
  { key: 'e_commerce_product_manager', name: 'E-commerce Product Manager' },
  { key: 'e_commerce_researcher', name: 'E-commerce Researcher' },
  { key: 'e_commerce_sales_lead', name: 'E-commerce Sales Lead' },
  { key: 'e_commerce_scientist', name: 'E-commerce Scientist' },
  { key: 'e_commerce_specialist', name: 'E-commerce Specialist' },
  { key: 'economist', name: 'Economist' },
  { key: 'editor', name: 'Editor' },
  { key: 'edtech_analyst', name: 'Edtech Analyst' },
  { key: 'edtech_architect', name: 'Edtech Architect' },
  { key: 'edtech_consultant', name: 'Edtech Consultant' },
  { key: 'edtech_designer', name: 'Edtech Designer' },
  { key: 'edtech_director', name: 'Edtech Director' },
  { key: 'edtech_engineer', name: 'Edtech Engineer' },
  { key: 'edtech_lead', name: 'Edtech Lead' },
  { key: 'edtech_manager', name: 'Edtech Manager' },
  { key: 'edtech_marketer', name: 'Edtech Marketer' },
  { key: 'edtech_operator', name: 'Edtech Operator' },
  { key: 'edtech_product_manager', name: 'Edtech Product Manager' },
  { key: 'edtech_researcher', name: 'Edtech Researcher' },
  { key: 'edtech_sales_lead', name: 'Edtech Sales Lead' },
  { key: 'edtech_scientist', name: 'Edtech Scientist' },
  { key: 'edtech_specialist', name: 'Edtech Specialist' },
  { key: 'electrical_engineer', name: 'Electrical Engineer' },
  { key: 'email_marketing_manager', name: 'Email Marketing Manager' },
  { key: 'embedded_engineer', name: 'Embedded Engineer' },
  { key: 'energy_analyst', name: 'Energy Analyst' },
  { key: 'energy_architect', name: 'Energy Architect' },
  { key: 'energy_consultant', name: 'Energy Consultant' },
  { key: 'energy_designer', name: 'Energy Designer' },
  { key: 'energy_director', name: 'Energy Director' },
  { key: 'energy_engineer', name: 'Energy Engineer' },
  { key: 'energy_lead', name: 'Energy Lead' },
  { key: 'energy_manager', name: 'Energy Manager' },
  { key: 'energy_marketer', name: 'Energy Marketer' },
  { key: 'energy_operator', name: 'Energy Operator' },
  { key: 'energy_product_manager', name: 'Energy Product Manager' },
  { key: 'energy_researcher', name: 'Energy Researcher' },
  { key: 'energy_sales_lead', name: 'Energy Sales Lead' },
  { key: 'energy_scientist', name: 'Energy Scientist' },
  { key: 'energy_specialist', name: 'Energy Specialist' },
  { key: 'engineer', name: 'Engineer' },
  { key: 'engineering_manager', name: 'Engineering Manager' },
  { key: 'enterprise_account_executive', name: 'Enterprise Account Executive' },
  { key: 'enterprise_analyst', name: 'Enterprise Analyst' },
  { key: 'enterprise_architect', name: 'Enterprise Architect' },
  { key: 'enterprise_consultant', name: 'Enterprise Consultant' },
  { key: 'enterprise_designer', name: 'Enterprise Designer' },
  { key: 'enterprise_director', name: 'Enterprise Director' },
  { key: 'enterprise_engineer', name: 'Enterprise Engineer' },
  { key: 'enterprise_lead', name: 'Enterprise Lead' },
  { key: 'enterprise_manager', name: 'Enterprise Manager' },
  { key: 'enterprise_marketer', name: 'Enterprise Marketer' },
  { key: 'enterprise_operator', name: 'Enterprise Operator' },
  { key: 'enterprise_product_manager', name: 'Enterprise Product Manager' },
  { key: 'enterprise_researcher', name: 'Enterprise Researcher' },
  { key: 'enterprise_sales_lead', name: 'Enterprise Sales Lead' },
  { key: 'enterprise_scientist', name: 'Enterprise Scientist' },
  { key: 'enterprise_specialist', name: 'Enterprise Specialist' },
  { key: 'entertainment_analyst', name: 'Entertainment Analyst' },
  { key: 'entertainment_architect', name: 'Entertainment Architect' },
  { key: 'entertainment_consultant', name: 'Entertainment Consultant' },
  { key: 'entertainment_designer', name: 'Entertainment Designer' },
  { key: 'entertainment_director', name: 'Entertainment Director' },
  { key: 'entertainment_engineer', name: 'Entertainment Engineer' },
  { key: 'entertainment_lead', name: 'Entertainment Lead' },
  { key: 'entertainment_manager', name: 'Entertainment Manager' },
  { key: 'entertainment_marketer', name: 'Entertainment Marketer' },
  { key: 'entertainment_operator', name: 'Entertainment Operator' },
  { key: 'entertainment_researcher', name: 'Entertainment Researcher' },
  { key: 'entertainment_sales_lead', name: 'Entertainment Sales Lead' },
  { key: 'entertainment_scientist', name: 'Entertainment Scientist' },
  { key: 'entertainment_specialist', name: 'Entertainment Specialist' },
  { key: 'entrepreneur', name: 'Entrepreneur' },
  { key: 'environmental_engineer', name: 'Environmental Engineer' },
  { key: 'erp_consultant', name: 'ERP Consultant' },
  { key: 'event_manager', name: 'Event Manager' },
  { key: 'evp', name: 'EVP' },
  { key: 'executive_assistant', name: 'Executive Assistant' },
  { key: 'executive_director', name: 'Executive Director' },
  { key: 'factory_worker', name: 'Factory Worker' },
  { key: 'family_office_investor', name: 'Family Office Investor' },
  { key: 'farmer', name: 'Farmer' },
  { key: 'fashion_analyst', name: 'Fashion Analyst' },
  { key: 'fashion_architect', name: 'Fashion Architect' },
  { key: 'fashion_consultant', name: 'Fashion Consultant' },
  { key: 'fashion_designer', name: 'Fashion Designer' },
  { key: 'fashion_director', name: 'Fashion Director' },
  { key: 'fashion_engineer', name: 'Fashion Engineer' },
  { key: 'fashion_lead', name: 'Fashion Lead' },
  { key: 'fashion_manager', name: 'Fashion Manager' },
  { key: 'fashion_marketer', name: 'Fashion Marketer' },
  { key: 'fashion_operator', name: 'Fashion Operator' },
  { key: 'fashion_product_manager', name: 'Fashion Product Manager' },
  { key: 'fashion_researcher', name: 'Fashion Researcher' },
  { key: 'fashion_sales_lead', name: 'Fashion Sales Lead' },
  { key: 'fashion_scientist', name: 'Fashion Scientist' },
  { key: 'fashion_specialist', name: 'Fashion Specialist' },
  { key: 'field_marketing_manager', name: 'Field Marketing Manager' },
  { key: 'film_analyst', name: 'Film Analyst' },
  { key: 'film_architect', name: 'Film Architect' },
  { key: 'film_consultant', name: 'Film Consultant' },
  { key: 'film_designer', name: 'Film Designer' },
  { key: 'film_director', name: 'Film Director' },
  { key: 'film_engineer', name: 'Film Engineer' },
  { key: 'film_lead', name: 'Film Lead' },
  { key: 'film_manager', name: 'Film Manager' },
  { key: 'film_marketer', name: 'Film Marketer' },
  { key: 'film_operator', name: 'Film Operator' },
  { key: 'film_product_manager', name: 'Film Product Manager' },
  { key: 'film_researcher', name: 'Film Researcher' },
  { key: 'film_sales_lead', name: 'Film Sales Lead' },
  { key: 'film_scientist', name: 'Film Scientist' },
  { key: 'film_specialist', name: 'Film Specialist' },
  { key: 'filmmaker', name: 'Filmmaker' },
  { key: 'finance_manager', name: 'Finance Manager' },
  { key: 'financial_advisor', name: 'Financial Advisor' },
  { key: 'financial_analyst', name: 'Financial Analyst' },
  { key: 'fintech_analyst', name: 'Fintech Analyst' },
  { key: 'fintech_architect', name: 'Fintech Architect' },
  { key: 'fintech_consultant', name: 'Fintech Consultant' },
  { key: 'fintech_designer', name: 'Fintech Designer' },
  { key: 'fintech_director', name: 'Fintech Director' },
  { key: 'fintech_engineer', name: 'Fintech Engineer' },
  { key: 'fintech_lead', name: 'Fintech Lead' },
  { key: 'fintech_manager', name: 'Fintech Manager' },
  { key: 'fintech_marketer', name: 'Fintech Marketer' },
  { key: 'fintech_operator', name: 'Fintech Operator' },
  { key: 'fintech_product_manager', name: 'Fintech Product Manager' },
  { key: 'fintech_researcher', name: 'Fintech Researcher' },
  { key: 'fintech_sales_lead', name: 'Fintech Sales Lead' },
  { key: 'fintech_scientist', name: 'Fintech Scientist' },
  { key: 'fintech_specialist', name: 'Fintech Specialist' },
  { key: 'firefighter', name: 'Firefighter' },
  { key: 'firmware_engineer', name: 'Firmware Engineer' },
  { key: 'flight_attendant', name: 'Flight Attendant' },
  { key: 'food_analyst', name: 'Food Analyst' },
  { key: 'food_architect', name: 'Food Architect' },
  { key: 'food_consultant', name: 'Food Consultant' },
  { key: 'food_designer', name: 'Food Designer' },
  { key: 'food_director', name: 'Food Director' },
  { key: 'food_engineer', name: 'Food Engineer' },
  { key: 'food_lead', name: 'Food Lead' },
  { key: 'food_manager', name: 'Food Manager' },
  { key: 'food_marketer', name: 'Food Marketer' },
  { key: 'food_operator', name: 'Food Operator' },
  { key: 'food_product_manager', name: 'Food Product Manager' },
  { key: 'food_researcher', name: 'Food Researcher' },
  { key: 'food_sales_lead', name: 'Food Sales Lead' },
  { key: 'food_scientist', name: 'Food Scientist' },
  { key: 'food_specialist', name: 'Food Specialist' },
  { key: 'founder', name: 'Founder' },
  { key: 'founding_designer', name: 'Founding Designer' },
  { key: 'founding_engineer', name: 'Founding Engineer' },
  { key: 'founding_product_manager', name: 'Founding Product Manager' },
  { key: 'fp_a_analyst', name: 'FP&A Analyst' },
  { key: 'fp_a_manager', name: 'FP&A Manager' },
  { key: 'fractional_ceo', name: 'Fractional CEO' },
  { key: 'fractional_cto', name: 'Fractional CTO' },
  { key: 'freelancer', name: 'Freelancer' },
  { key: 'frontend_engineer', name: 'Frontend Engineer' },
  { key: 'full_stack_engineer', name: 'Full Stack Engineer' },
  { key: 'fullstack_engineer', name: 'Fullstack Engineer' },
  { key: 'fundraiser', name: 'Fundraiser' },
  { key: 'game_designer', name: 'Game Designer' },
  { key: 'game_engineer', name: 'Game Engineer' },
  { key: 'gaming_analyst', name: 'Gaming Analyst' },
  { key: 'gaming_architect', name: 'Gaming Architect' },
  { key: 'gaming_consultant', name: 'Gaming Consultant' },
  { key: 'gaming_designer', name: 'Gaming Designer' },
  { key: 'gaming_director', name: 'Gaming Director' },
  { key: 'gaming_engineer', name: 'Gaming Engineer' },
  { key: 'gaming_lead', name: 'Gaming Lead' },
  { key: 'gaming_manager', name: 'Gaming Manager' },
  { key: 'gaming_marketer', name: 'Gaming Marketer' },
  { key: 'gaming_operator', name: 'Gaming Operator' },
  { key: 'gaming_product_manager', name: 'Gaming Product Manager' },
  { key: 'gaming_researcher', name: 'Gaming Researcher' },
  { key: 'gaming_sales_lead', name: 'Gaming Sales Lead' },
  { key: 'gaming_scientist', name: 'Gaming Scientist' },
  { key: 'gaming_specialist', name: 'Gaming Specialist' },
  { key: 'general_counsel', name: 'General Counsel' },
  { key: 'general_partner', name: 'General Partner' },
  { key: 'gig_worker', name: 'Gig Worker' },
  { key: 'government_analyst', name: 'Government Analyst' },
  { key: 'government_architect', name: 'Government Architect' },
  { key: 'government_consultant', name: 'Government Consultant' },
  { key: 'government_designer', name: 'Government Designer' },
  { key: 'government_director', name: 'Government Director' },
  { key: 'government_engineer', name: 'Government Engineer' },
  { key: 'government_lead', name: 'Government Lead' },
  { key: 'government_manager', name: 'Government Manager' },
  { key: 'government_marketer', name: 'Government Marketer' },
  { key: 'government_official', name: 'Government Official' },
  { key: 'government_operator', name: 'Government Operator' },
  { key: 'government_product_manager', name: 'Government Product Manager' },
  { key: 'government_researcher', name: 'Government Researcher' },
  { key: 'government_sales_lead', name: 'Government Sales Lead' },
  { key: 'government_scientist', name: 'Government Scientist' },
  { key: 'government_specialist', name: 'Government Specialist' },
  { key: 'graphic_designer', name: 'Graphic Designer' },
  { key: 'graphics_engineer', name: 'Graphics Engineer' },
  { key: 'group_product_manager', name: 'Group Product Manager' },
  { key: 'growth_analyst', name: 'Growth Analyst' },
  { key: 'growth_manager', name: 'Growth Manager' },
  { key: 'growth_marketer', name: 'Growth Marketer' },
  { key: 'growth_product_manager', name: 'Growth Product Manager' },
  { key: 'hardware_analyst', name: 'Hardware Analyst' },
  { key: 'hardware_architect', name: 'Hardware Architect' },
  { key: 'hardware_consultant', name: 'Hardware Consultant' },
  { key: 'hardware_designer', name: 'Hardware Designer' },
  { key: 'hardware_director', name: 'Hardware Director' },
  { key: 'hardware_engineer', name: 'Hardware Engineer' },
  { key: 'hardware_lead', name: 'Hardware Lead' },
  { key: 'hardware_manager', name: 'Hardware Manager' },
  { key: 'hardware_marketer', name: 'Hardware Marketer' },
  { key: 'hardware_operator', name: 'Hardware Operator' },
  { key: 'hardware_product_manager', name: 'Hardware Product Manager' },
  { key: 'hardware_researcher', name: 'Hardware Researcher' },
  { key: 'hardware_sales_lead', name: 'Hardware Sales Lead' },
  { key: 'hardware_scientist', name: 'Hardware Scientist' },
  { key: 'hardware_specialist', name: 'Hardware Specialist' },
  { key: 'head_of_data', name: 'Head of Data' },
  { key: 'head_of_design', name: 'Head of Design' },
  { key: 'head_of_engineering', name: 'Head of Engineering' },
  { key: 'head_of_growth', name: 'Head of Growth' },
  { key: 'head_of_operations', name: 'Head of Operations' },
  { key: 'head_of_people', name: 'Head of People' },
  { key: 'head_of_product', name: 'Head of Product' },
  { key: 'head_of_sales', name: 'Head of Sales' },
  { key: 'healthcare_analyst', name: 'Healthcare Analyst' },
  { key: 'healthcare_architect', name: 'Healthcare Architect' },
  { key: 'healthcare_consultant', name: 'Healthcare Consultant' },
  { key: 'healthcare_designer', name: 'Healthcare Designer' },
  { key: 'healthcare_director', name: 'Healthcare Director' },
  { key: 'healthcare_engineer', name: 'Healthcare Engineer' },
  { key: 'healthcare_lead', name: 'Healthcare Lead' },
  { key: 'healthcare_manager', name: 'Healthcare Manager' },
  { key: 'healthcare_marketer', name: 'Healthcare Marketer' },
  { key: 'healthcare_operator', name: 'Healthcare Operator' },
  { key: 'healthcare_product_manager', name: 'Healthcare Product Manager' },
  { key: 'healthcare_researcher', name: 'Healthcare Researcher' },
  { key: 'healthcare_sales_lead', name: 'Healthcare Sales Lead' },
  { key: 'healthcare_scientist', name: 'Healthcare Scientist' },
  { key: 'healthcare_specialist', name: 'Healthcare Specialist' },
  { key: 'healthtech_analyst', name: 'Healthtech Analyst' },
  { key: 'healthtech_architect', name: 'Healthtech Architect' },
  { key: 'healthtech_consultant', name: 'Healthtech Consultant' },
  { key: 'healthtech_designer', name: 'Healthtech Designer' },
  { key: 'healthtech_director', name: 'Healthtech Director' },
  { key: 'healthtech_engineer', name: 'Healthtech Engineer' },
  { key: 'healthtech_lead', name: 'Healthtech Lead' },
  { key: 'healthtech_manager', name: 'Healthtech Manager' },
  { key: 'healthtech_marketer', name: 'Healthtech Marketer' },
  { key: 'healthtech_operator', name: 'Healthtech Operator' },
  { key: 'healthtech_product_manager', name: 'Healthtech Product Manager' },
  { key: 'healthtech_researcher', name: 'Healthtech Researcher' },
  { key: 'healthtech_sales_lead', name: 'Healthtech Sales Lead' },
  { key: 'healthtech_scientist', name: 'Healthtech Scientist' },
  { key: 'healthtech_specialist', name: 'Healthtech Specialist' },
  { key: 'hedge_fund_analyst', name: 'Hedge Fund Analyst' },
  { key: 'help_desk_specialist', name: 'Help Desk Specialist' },
  { key: 'homemaker', name: 'Homemaker' },
  { key: 'hospitality_analyst', name: 'Hospitality Analyst' },
  { key: 'hospitality_architect', name: 'Hospitality Architect' },
  { key: 'hospitality_consultant', name: 'Hospitality Consultant' },
  { key: 'hospitality_designer', name: 'Hospitality Designer' },
  { key: 'hospitality_director', name: 'Hospitality Director' },
  { key: 'hospitality_engineer', name: 'Hospitality Engineer' },
  { key: 'hospitality_lead', name: 'Hospitality Lead' },
  { key: 'hospitality_manager', name: 'Hospitality Manager' },
  { key: 'hospitality_marketer', name: 'Hospitality Marketer' },
  { key: 'hospitality_operator', name: 'Hospitality Operator' },
  { key: 'hospitality_product_manager', name: 'Hospitality Product Manager' },
  { key: 'hospitality_researcher', name: 'Hospitality Researcher' },
  { key: 'hospitality_sales_lead', name: 'Hospitality Sales Lead' },
  { key: 'hospitality_scientist', name: 'Hospitality Scientist' },
  { key: 'hospitality_specialist', name: 'Hospitality Specialist' },
  { key: 'hotel_manager', name: 'Hotel Manager' },
  { key: 'hr_manager', name: 'HR Manager' },
  { key: 'hr_tech_analyst', name: 'HR Tech Analyst' },
  { key: 'hr_tech_architect', name: 'HR Tech Architect' },
  { key: 'hr_tech_consultant', name: 'HR Tech Consultant' },
  { key: 'hr_tech_designer', name: 'HR Tech Designer' },
  { key: 'hr_tech_director', name: 'HR Tech Director' },
  { key: 'hr_tech_engineer', name: 'HR Tech Engineer' },
  { key: 'hr_tech_lead', name: 'HR Tech Lead' },
  { key: 'hr_tech_manager', name: 'HR Tech Manager' },
  { key: 'hr_tech_marketer', name: 'HR Tech Marketer' },
  { key: 'hr_tech_operator', name: 'HR Tech Operator' },
  { key: 'hr_tech_product_manager', name: 'HR Tech Product Manager' },
  { key: 'hr_tech_researcher', name: 'HR Tech Researcher' },
  { key: 'hr_tech_sales_lead', name: 'HR Tech Sales Lead' },
  { key: 'hr_tech_scientist', name: 'HR Tech Scientist' },
  { key: 'hr_tech_specialist', name: 'HR Tech Specialist' },
  { key: 'identity_analyst', name: 'Identity Analyst' },
  { key: 'identity_architect', name: 'Identity Architect' },
  { key: 'identity_consultant', name: 'Identity Consultant' },
  { key: 'identity_designer', name: 'Identity Designer' },
  { key: 'identity_director', name: 'Identity Director' },
  { key: 'identity_engineer', name: 'Identity Engineer' },
  { key: 'identity_lead', name: 'Identity Lead' },
  { key: 'identity_manager', name: 'Identity Manager' },
  { key: 'identity_marketer', name: 'Identity Marketer' },
  { key: 'identity_operator', name: 'Identity Operator' },
  { key: 'identity_product_manager', name: 'Identity Product Manager' },
  { key: 'identity_researcher', name: 'Identity Researcher' },
  { key: 'identity_sales_lead', name: 'Identity Sales Lead' },
  { key: 'identity_scientist', name: 'Identity Scientist' },
  { key: 'identity_specialist', name: 'Identity Specialist' },
  { key: 'illustrator', name: 'Illustrator' },
  { key: 'incubator_director', name: 'Incubator Director' },
  { key: 'indie_hacker', name: 'Indie Hacker' },
  { key: 'industrial_designer', name: 'Industrial Designer' },
  { key: 'influencer', name: 'Influencer' },
  { key: 'information_security_analyst', name: 'Information Security Analyst' },
  { key: 'infrastructure_analyst', name: 'Infrastructure Analyst' },
  { key: 'infrastructure_architect', name: 'Infrastructure Architect' },
  { key: 'infrastructure_consultant', name: 'Infrastructure Consultant' },
  { key: 'infrastructure_designer', name: 'Infrastructure Designer' },
  { key: 'infrastructure_director', name: 'Infrastructure Director' },
  { key: 'infrastructure_engineer', name: 'Infrastructure Engineer' },
  { key: 'infrastructure_lead', name: 'Infrastructure Lead' },
  { key: 'infrastructure_manager', name: 'Infrastructure Manager' },
  { key: 'infrastructure_marketer', name: 'Infrastructure Marketer' },
  { key: 'infrastructure_operator', name: 'Infrastructure Operator' },
  { key: 'infrastructure_researcher', name: 'Infrastructure Researcher' },
  { key: 'infrastructure_sales_lead', name: 'Infrastructure Sales Lead' },
  { key: 'infrastructure_scientist', name: 'Infrastructure Scientist' },
  { key: 'infrastructure_specialist', name: 'Infrastructure Specialist' },
  { key: 'inside_sales_representative', name: 'Inside Sales Representative' },
  { key: 'insights_analyst', name: 'Insights Analyst' },
  { key: 'insurance_agent', name: 'Insurance Agent' },
  { key: 'insurance_analyst', name: 'Insurance Analyst' },
  { key: 'insurance_architect', name: 'Insurance Architect' },
  { key: 'insurance_consultant', name: 'Insurance Consultant' },
  { key: 'insurance_designer', name: 'Insurance Designer' },
  { key: 'insurance_director', name: 'Insurance Director' },
  { key: 'insurance_engineer', name: 'Insurance Engineer' },
  { key: 'insurance_lead', name: 'Insurance Lead' },
  { key: 'insurance_manager', name: 'Insurance Manager' },
  { key: 'insurance_marketer', name: 'Insurance Marketer' },
  { key: 'insurance_operator', name: 'Insurance Operator' },
  { key: 'insurance_product_manager', name: 'Insurance Product Manager' },
  { key: 'insurance_researcher', name: 'Insurance Researcher' },
  { key: 'insurance_sales_lead', name: 'Insurance Sales Lead' },
  { key: 'insurance_scientist', name: 'Insurance Scientist' },
  { key: 'insurance_specialist', name: 'Insurance Specialist' },
  { key: 'integration_engineer', name: 'Integration Engineer' },
  { key: 'interaction_designer', name: 'Interaction Designer' },
  { key: 'interim_ceo', name: 'Interim CEO' },
  { key: 'intern', name: 'Intern' },
  { key: 'internal_auditor', name: 'Internal Auditor' },
  { key: 'interpreter', name: 'Interpreter' },
  { key: 'investment_banker', name: 'Investment Banker' },
  { key: 'investor', name: 'Investor' },
  { key: 'ios_engineer', name: 'iOS Engineer' },
  { key: 'it_manager', name: 'IT Manager' },
  { key: 'journalist', name: 'Journalist' },
  { key: 'judge', name: 'Judge' },
  { key: 'junior_account_executive', name: 'Junior Account Executive' },
  { key: 'junior_backend_engineer', name: 'Junior Backend Engineer' },
  { key: 'junior_business_analyst', name: 'Junior Business Analyst' },
  { key: 'junior_consultant', name: 'Junior Consultant' },
  { key: 'junior_content_writer', name: 'Junior Content Writer' },
  { key: 'junior_data_analyst', name: 'Junior Data Analyst' },
  { key: 'junior_data_engineer', name: 'Junior Data Engineer' },
  { key: 'junior_data_scientist', name: 'Junior Data Scientist' },
  { key: 'junior_designer', name: 'Junior Designer' },
  { key: 'junior_devops_engineer', name: 'Junior DevOps Engineer' },
  { key: 'junior_finance_manager', name: 'Junior Finance Manager' },
  { key: 'junior_frontend_engineer', name: 'Junior Frontend Engineer' },
  { key: 'junior_full_stack_engineer', name: 'Junior Full Stack Engineer' },
  { key: 'junior_fullstack_engineer', name: 'Junior Fullstack Engineer' },
  { key: 'junior_growth_manager', name: 'Junior Growth Manager' },
  { key: 'junior_marketing_manager', name: 'Junior Marketing Manager' },
  { key: 'junior_ml_engineer', name: 'Junior ML Engineer' },
  { key: 'junior_mobile_engineer', name: 'Junior Mobile Engineer' },
  { key: 'junior_operations_manager', name: 'Junior Operations Manager' },
  { key: 'junior_product_designer', name: 'Junior Product Designer' },
  { key: 'junior_product_manager', name: 'Junior Product Manager' },
  { key: 'junior_program_manager', name: 'Junior Program Manager' },
  { key: 'junior_project_manager', name: 'Junior Project Manager' },
  { key: 'junior_qa_engineer', name: 'Junior QA Engineer' },
  { key: 'junior_recruiter', name: 'Junior Recruiter' },
  { key: 'junior_researcher', name: 'Junior Researcher' },
  { key: 'junior_sales_manager', name: 'Junior Sales Manager' },
  { key: 'junior_security_engineer', name: 'Junior Security Engineer' },
  { key: 'junior_software_engineer', name: 'Junior Software Engineer' },
  { key: 'junior_strategy_manager', name: 'Junior Strategy Manager' },
  { key: 'junior_ux_designer', name: 'Junior UX Designer' },
  { key: 'lab_technician', name: 'Lab Technician' },
  { key: 'lawyer', name: 'Lawyer' },
  { key: 'lead_account_executive', name: 'Lead Account Executive' },
  { key: 'lead_backend_engineer', name: 'Lead Backend Engineer' },
  { key: 'lead_business_analyst', name: 'Lead Business Analyst' },
  { key: 'lead_consultant', name: 'Lead Consultant' },
  { key: 'lead_content_writer', name: 'Lead Content Writer' },
  { key: 'lead_data_analyst', name: 'Lead Data Analyst' },
  { key: 'lead_data_engineer', name: 'Lead Data Engineer' },
  { key: 'lead_data_scientist', name: 'Lead Data Scientist' },
  { key: 'lead_designer', name: 'Lead Designer' },
  { key: 'lead_devops_engineer', name: 'Lead DevOps Engineer' },
  { key: 'lead_finance_manager', name: 'Lead Finance Manager' },
  { key: 'lead_frontend_engineer', name: 'Lead Frontend Engineer' },
  { key: 'lead_full_stack_engineer', name: 'Lead Full Stack Engineer' },
  { key: 'lead_fullstack_engineer', name: 'Lead Fullstack Engineer' },
  { key: 'lead_growth_manager', name: 'Lead Growth Manager' },
  { key: 'lead_marketing_manager', name: 'Lead Marketing Manager' },
  { key: 'lead_ml_engineer', name: 'Lead ML Engineer' },
  { key: 'lead_mobile_engineer', name: 'Lead Mobile Engineer' },
  { key: 'lead_operations_manager', name: 'Lead Operations Manager' },
  { key: 'lead_product_designer', name: 'Lead Product Designer' },
  { key: 'lead_product_manager', name: 'Lead Product Manager' },
  { key: 'lead_program_manager', name: 'Lead Program Manager' },
  { key: 'lead_project_manager', name: 'Lead Project Manager' },
  { key: 'lead_qa_engineer', name: 'Lead QA Engineer' },
  { key: 'lead_recruiter', name: 'Lead Recruiter' },
  { key: 'lead_researcher', name: 'Lead Researcher' },
  { key: 'lead_sales_manager', name: 'Lead Sales Manager' },
  { key: 'lead_security_engineer', name: 'Lead Security Engineer' },
  { key: 'lead_software_engineer', name: 'Lead Software Engineer' },
  { key: 'lead_strategy_manager', name: 'Lead Strategy Manager' },
  { key: 'lead_ux_designer', name: 'Lead UX Designer' },
  { key: 'lecturer', name: 'Lecturer' },
  { key: 'legal_analyst', name: 'Legal Analyst' },
  { key: 'legal_architect', name: 'Legal Architect' },
  { key: 'legal_consultant', name: 'Legal Consultant' },
  { key: 'legal_designer', name: 'Legal Designer' },
  { key: 'legal_director', name: 'Legal Director' },
  { key: 'legal_engineer', name: 'Legal Engineer' },
  { key: 'legal_lead', name: 'Legal Lead' },
  { key: 'legal_manager', name: 'Legal Manager' },
  { key: 'legal_marketer', name: 'Legal Marketer' },
  { key: 'legal_operator', name: 'Legal Operator' },
  { key: 'legal_product_manager', name: 'Legal Product Manager' },
  { key: 'legal_researcher', name: 'Legal Researcher' },
  { key: 'legal_sales_lead', name: 'Legal Sales Lead' },
  { key: 'legal_scientist', name: 'Legal Scientist' },
  { key: 'legal_specialist', name: 'Legal Specialist' },
  { key: 'level_designer', name: 'Level Designer' },
  { key: 'librarian', name: 'Librarian' },
  { key: 'lifecycle_marketing_manager', name: 'Lifecycle Marketing Manager' },
  { key: 'limited_partner', name: 'Limited Partner' },
  { key: 'localization_manager', name: 'Localization Manager' },
  { key: 'logistics_analyst', name: 'Logistics Analyst' },
  { key: 'logistics_architect', name: 'Logistics Architect' },
  { key: 'logistics_consultant', name: 'Logistics Consultant' },
  { key: 'logistics_designer', name: 'Logistics Designer' },
  { key: 'logistics_director', name: 'Logistics Director' },
  { key: 'logistics_engineer', name: 'Logistics Engineer' },
  { key: 'logistics_lead', name: 'Logistics Lead' },
  { key: 'logistics_manager', name: 'Logistics Manager' },
  { key: 'logistics_marketer', name: 'Logistics Marketer' },
  { key: 'logistics_operator', name: 'Logistics Operator' },
  { key: 'logistics_product_manager', name: 'Logistics Product Manager' },
  { key: 'logistics_researcher', name: 'Logistics Researcher' },
  { key: 'logistics_sales_lead', name: 'Logistics Sales Lead' },
  { key: 'logistics_scientist', name: 'Logistics Scientist' },
  { key: 'logistics_specialist', name: 'Logistics Specialist' },
  { key: 'low_code_developer', name: 'Low-Code Developer' },
  { key: 'machine_learning_engineer', name: 'Machine Learning Engineer' },
  { key: 'maker', name: 'Maker' },
  { key: 'management_consultant', name: 'Management Consultant' },
  { key: 'managing_director', name: 'Managing Director' },
  { key: 'managing_partner', name: 'Managing Partner' },
  { key: 'manufacturing_analyst', name: 'Manufacturing Analyst' },
  { key: 'manufacturing_architect', name: 'Manufacturing Architect' },
  { key: 'manufacturing_consultant', name: 'Manufacturing Consultant' },
  { key: 'manufacturing_designer', name: 'Manufacturing Designer' },
  { key: 'manufacturing_director', name: 'Manufacturing Director' },
  { key: 'manufacturing_engineer', name: 'Manufacturing Engineer' },
  { key: 'manufacturing_lead', name: 'Manufacturing Lead' },
  { key: 'manufacturing_manager', name: 'Manufacturing Manager' },
  { key: 'manufacturing_marketer', name: 'Manufacturing Marketer' },
  { key: 'manufacturing_operator', name: 'Manufacturing Operator' },
  { key: 'manufacturing_researcher', name: 'Manufacturing Researcher' },
  { key: 'manufacturing_sales_lead', name: 'Manufacturing Sales Lead' },
  { key: 'manufacturing_scientist', name: 'Manufacturing Scientist' },
  { key: 'manufacturing_specialist', name: 'Manufacturing Specialist' },
  { key: 'marketing_analyst', name: 'Marketing Analyst' },
  { key: 'marketing_manager', name: 'Marketing Manager' },
  { key: 'marketplace_analyst', name: 'Marketplace Analyst' },
  { key: 'marketplace_architect', name: 'Marketplace Architect' },
  { key: 'marketplace_consultant', name: 'Marketplace Consultant' },
  { key: 'marketplace_designer', name: 'Marketplace Designer' },
  { key: 'marketplace_director', name: 'Marketplace Director' },
  { key: 'marketplace_engineer', name: 'Marketplace Engineer' },
  { key: 'marketplace_lead', name: 'Marketplace Lead' },
  { key: 'marketplace_manager', name: 'Marketplace Manager' },
  { key: 'marketplace_marketer', name: 'Marketplace Marketer' },
  { key: 'marketplace_operator', name: 'Marketplace Operator' },
  { key: 'marketplace_product_manager', name: 'Marketplace Product Manager' },
  { key: 'marketplace_researcher', name: 'Marketplace Researcher' },
  { key: 'marketplace_sales_lead', name: 'Marketplace Sales Lead' },
  { key: 'marketplace_scientist', name: 'Marketplace Scientist' },
  { key: 'marketplace_specialist', name: 'Marketplace Specialist' },
  { key: 'mechanical_engineer', name: 'Mechanical Engineer' },
  { key: 'media_analyst', name: 'Media Analyst' },
  { key: 'media_architect', name: 'Media Architect' },
  { key: 'media_consultant', name: 'Media Consultant' },
  { key: 'media_designer', name: 'Media Designer' },
  { key: 'media_director', name: 'Media Director' },
  { key: 'media_engineer', name: 'Media Engineer' },
  { key: 'media_lead', name: 'Media Lead' },
  { key: 'media_manager', name: 'Media Manager' },
  { key: 'media_marketer', name: 'Media Marketer' },
  { key: 'media_operator', name: 'Media Operator' },
  { key: 'media_product_manager', name: 'Media Product Manager' },
  { key: 'media_researcher', name: 'Media Researcher' },
  { key: 'media_sales_lead', name: 'Media Sales Lead' },
  { key: 'media_scientist', name: 'Media Scientist' },
  { key: 'media_specialist', name: 'Media Specialist' },
  { key: 'medical_doctor', name: 'Medical Doctor' },
  { key: 'military', name: 'Military' },
  { key: 'ml_engineer', name: 'ML Engineer' },
  { key: 'mlops_engineer', name: 'MLOps Engineer' },
  { key: 'mobile_analyst', name: 'Mobile Analyst' },
  { key: 'mobile_architect', name: 'Mobile Architect' },
  { key: 'mobile_consultant', name: 'Mobile Consultant' },
  { key: 'mobile_designer', name: 'Mobile Designer' },
  { key: 'mobile_director', name: 'Mobile Director' },
  { key: 'mobile_engineer', name: 'Mobile Engineer' },
  { key: 'mobile_lead', name: 'Mobile Lead' },
  { key: 'mobile_manager', name: 'Mobile Manager' },
  { key: 'mobile_marketer', name: 'Mobile Marketer' },
  { key: 'mobile_operator', name: 'Mobile Operator' },
  { key: 'mobile_product_manager', name: 'Mobile Product Manager' },
  { key: 'mobile_researcher', name: 'Mobile Researcher' },
  { key: 'mobile_sales_lead', name: 'Mobile Sales Lead' },
  { key: 'mobile_scientist', name: 'Mobile Scientist' },
  { key: 'mobile_specialist', name: 'Mobile Specialist' },
  { key: 'motion_designer', name: 'Motion Designer' },
  { key: 'music_analyst', name: 'Music Analyst' },
  { key: 'music_architect', name: 'Music Architect' },
  { key: 'music_consultant', name: 'Music Consultant' },
  { key: 'music_designer', name: 'Music Designer' },
  { key: 'music_director', name: 'Music Director' },
  { key: 'music_engineer', name: 'Music Engineer' },
  { key: 'music_lead', name: 'Music Lead' },
  { key: 'music_manager', name: 'Music Manager' },
  { key: 'music_marketer', name: 'Music Marketer' },
  { key: 'music_operator', name: 'Music Operator' },
  { key: 'music_producer', name: 'Music Producer' },
  { key: 'music_product_manager', name: 'Music Product Manager' },
  { key: 'music_researcher', name: 'Music Researcher' },
  { key: 'music_sales_lead', name: 'Music Sales Lead' },
  { key: 'music_scientist', name: 'Music Scientist' },
  { key: 'music_specialist', name: 'Music Specialist' },
  { key: 'narrative_designer', name: 'Narrative Designer' },
  { key: 'network_engineer', name: 'Network Engineer' },
  { key: 'networking_analyst', name: 'Networking Analyst' },
  { key: 'networking_architect', name: 'Networking Architect' },
  { key: 'networking_consultant', name: 'Networking Consultant' },
  { key: 'networking_designer', name: 'Networking Designer' },
  { key: 'networking_director', name: 'Networking Director' },
  { key: 'networking_engineer', name: 'Networking Engineer' },
  { key: 'networking_lead', name: 'Networking Lead' },
  { key: 'networking_manager', name: 'Networking Manager' },
  { key: 'networking_marketer', name: 'Networking Marketer' },
  { key: 'networking_operator', name: 'Networking Operator' },
  { key: 'networking_product_manager', name: 'Networking Product Manager' },
  { key: 'networking_researcher', name: 'Networking Researcher' },
  { key: 'networking_sales_lead', name: 'Networking Sales Lead' },
  { key: 'networking_scientist', name: 'Networking Scientist' },
  { key: 'networking_specialist', name: 'Networking Specialist' },
  { key: 'newsletter_writer', name: 'Newsletter Writer' },
  { key: 'nlp_engineer', name: 'NLP Engineer' },
  { key: 'no_code_developer', name: 'No-Code Developer' },
  { key: 'non_technical_founder', name: 'Non-technical Founder' },
  { key: 'nonprofit_analyst', name: 'Nonprofit Analyst' },
  { key: 'nonprofit_architect', name: 'Nonprofit Architect' },
  { key: 'nonprofit_consultant', name: 'Nonprofit Consultant' },
  { key: 'nonprofit_designer', name: 'Nonprofit Designer' },
  { key: 'nonprofit_director', name: 'Nonprofit Director' },
  { key: 'nonprofit_engineer', name: 'Nonprofit Engineer' },
  { key: 'nonprofit_lead', name: 'Nonprofit Lead' },
  { key: 'nonprofit_manager', name: 'Nonprofit Manager' },
  { key: 'nonprofit_marketer', name: 'Nonprofit Marketer' },
  { key: 'nonprofit_operator', name: 'Nonprofit Operator' },
  { key: 'nonprofit_product_manager', name: 'Nonprofit Product Manager' },
  { key: 'nonprofit_researcher', name: 'Nonprofit Researcher' },
  { key: 'nonprofit_sales_lead', name: 'Nonprofit Sales Lead' },
  { key: 'nonprofit_scientist', name: 'Nonprofit Scientist' },
  { key: 'nonprofit_specialist', name: 'Nonprofit Specialist' },
  { key: 'notion_consultant', name: 'Notion Consultant' },
  { key: 'nurse', name: 'Nurse' },
  { key: 'office_manager', name: 'Office Manager' },
  { key: 'open_source_maintainer', name: 'Open Source Maintainer' },
  { key: 'operations_analyst', name: 'Operations Analyst' },
  { key: 'operations_manager', name: 'Operations Manager' },
  { key: 'operator', name: 'Operator' },
  { key: 'partner', name: 'Partner' },
  { key: 'partnerships_manager', name: 'Partnerships Manager' },
  { key: 'payments_analyst', name: 'Payments Analyst' },
  { key: 'payments_architect', name: 'Payments Architect' },
  { key: 'payments_consultant', name: 'Payments Consultant' },
  { key: 'payments_designer', name: 'Payments Designer' },
  { key: 'payments_director', name: 'Payments Director' },
  { key: 'payments_engineer', name: 'Payments Engineer' },
  { key: 'payments_lead', name: 'Payments Lead' },
  { key: 'payments_manager', name: 'Payments Manager' },
  { key: 'payments_marketer', name: 'Payments Marketer' },
  { key: 'payments_operator', name: 'Payments Operator' },
  { key: 'payments_product_manager', name: 'Payments Product Manager' },
  { key: 'payments_researcher', name: 'Payments Researcher' },
  { key: 'payments_sales_lead', name: 'Payments Sales Lead' },
  { key: 'payments_scientist', name: 'Payments Scientist' },
  { key: 'payments_specialist', name: 'Payments Specialist' },
  { key: 'penetration_tester', name: 'Penetration Tester' },
  { key: 'people_manager', name: 'People Manager' },
  { key: 'people_operations_manager', name: 'People Operations Manager' },
  { key: 'performance_marketer', name: 'Performance Marketer' },
  { key: 'personal_trainer', name: 'Personal Trainer' },
  { key: 'pharmacist', name: 'Pharmacist' },
  { key: 'phd_student', name: 'PhD Student' },
  { key: 'photographer', name: 'Photographer' },
  { key: 'physician', name: 'Physician' },
  { key: 'pilot', name: 'Pilot' },
  { key: 'platform_analyst', name: 'Platform Analyst' },
  { key: 'platform_architect', name: 'Platform Architect' },
  { key: 'platform_consultant', name: 'Platform Consultant' },
  { key: 'platform_designer', name: 'Platform Designer' },
  { key: 'platform_director', name: 'Platform Director' },
  { key: 'platform_engineer', name: 'Platform Engineer' },
  { key: 'platform_lead', name: 'Platform Lead' },
  { key: 'platform_manager', name: 'Platform Manager' },
  { key: 'platform_marketer', name: 'Platform Marketer' },
  { key: 'platform_operator', name: 'Platform Operator' },
  { key: 'platform_product_manager', name: 'Platform Product Manager' },
  { key: 'platform_researcher', name: 'Platform Researcher' },
  { key: 'platform_sales_lead', name: 'Platform Sales Lead' },
  { key: 'platform_scientist', name: 'Platform Scientist' },
  { key: 'platform_specialist', name: 'Platform Specialist' },
  { key: 'podcaster', name: 'Podcaster' },
  { key: 'police_officer', name: 'Police Officer' },
  { key: 'policy_analyst', name: 'Policy Analyst' },
  { key: 'politician', name: 'Politician' },
  { key: 'portfolio_manager', name: 'Portfolio Manager' },
  { key: 'postdoctoral_researcher', name: 'Postdoctoral Researcher' },
  { key: 'pr_manager', name: 'PR Manager' },
  { key: 'president', name: 'President' },
  { key: 'principal_account_executive', name: 'Principal Account Executive' },
  { key: 'principal_architect', name: 'Principal Architect' },
  { key: 'principal_backend_engineer', name: 'Principal Backend Engineer' },
  { key: 'principal_business_analyst', name: 'Principal Business Analyst' },
  { key: 'principal_consultant', name: 'Principal Consultant' },
  { key: 'principal_content_writer', name: 'Principal Content Writer' },
  { key: 'principal_data_analyst', name: 'Principal Data Analyst' },
  { key: 'principal_data_engineer', name: 'Principal Data Engineer' },
  { key: 'principal_data_scientist', name: 'Principal Data Scientist' },
  { key: 'principal_designer', name: 'Principal Designer' },
  { key: 'principal_devops_engineer', name: 'Principal DevOps Engineer' },
  { key: 'principal_finance_manager', name: 'Principal Finance Manager' },
  { key: 'principal_frontend_engineer', name: 'Principal Frontend Engineer' },
  { key: 'principal_fullstack_engineer', name: 'Principal Fullstack Engineer' },
  { key: 'principal_growth_manager', name: 'Principal Growth Manager' },
  { key: 'principal_marketing_manager', name: 'Principal Marketing Manager' },
  { key: 'principal_ml_engineer', name: 'Principal ML Engineer' },
  { key: 'principal_mobile_engineer', name: 'Principal Mobile Engineer' },
  { key: 'principal_operations_manager', name: 'Principal Operations Manager' },
  { key: 'principal_product_designer', name: 'Principal Product Designer' },
  { key: 'principal_product_manager', name: 'Principal Product Manager' },
  { key: 'principal_program_manager', name: 'Principal Program Manager' },
  { key: 'principal_project_manager', name: 'Principal Project Manager' },
  { key: 'principal_qa_engineer', name: 'Principal QA Engineer' },
  { key: 'principal_recruiter', name: 'Principal Recruiter' },
  { key: 'principal_researcher', name: 'Principal Researcher' },
  { key: 'principal_sales_manager', name: 'Principal Sales Manager' },
  { key: 'principal_security_engineer', name: 'Principal Security Engineer' },
  { key: 'principal_software_engineer', name: 'Principal Software Engineer' },
  { key: 'principal_strategy_manager', name: 'Principal Strategy Manager' },
  { key: 'principal_ux_designer', name: 'Principal UX Designer' },
  { key: 'privacy_analyst', name: 'Privacy Analyst' },
  { key: 'privacy_architect', name: 'Privacy Architect' },
  { key: 'privacy_consultant', name: 'Privacy Consultant' },
  { key: 'privacy_counsel', name: 'Privacy Counsel' },
  { key: 'privacy_designer', name: 'Privacy Designer' },
  { key: 'privacy_director', name: 'Privacy Director' },
  { key: 'privacy_engineer', name: 'Privacy Engineer' },
  { key: 'privacy_lead', name: 'Privacy Lead' },
  { key: 'privacy_manager', name: 'Privacy Manager' },
  { key: 'privacy_marketer', name: 'Privacy Marketer' },
  { key: 'privacy_operator', name: 'Privacy Operator' },
  { key: 'privacy_product_manager', name: 'Privacy Product Manager' },
  { key: 'privacy_researcher', name: 'Privacy Researcher' },
  { key: 'privacy_sales_lead', name: 'Privacy Sales Lead' },
  { key: 'privacy_scientist', name: 'Privacy Scientist' },
  { key: 'privacy_specialist', name: 'Privacy Specialist' },
  { key: 'product_designer', name: 'Product Designer' },
  { key: 'product_marketing_manager', name: 'Product Marketing Manager' },
  { key: 'program_manager', name: 'Program Manager' },
  { key: 'project_manager', name: 'Project Manager' },
  { key: 'proptech_analyst', name: 'PropTech Analyst' },
  { key: 'proptech_architect', name: 'PropTech Architect' },
  { key: 'proptech_consultant', name: 'PropTech Consultant' },
  { key: 'proptech_designer', name: 'PropTech Designer' },
  { key: 'proptech_director', name: 'PropTech Director' },
  { key: 'proptech_engineer', name: 'PropTech Engineer' },
  { key: 'proptech_lead', name: 'PropTech Lead' },
  { key: 'proptech_manager', name: 'PropTech Manager' },
  { key: 'proptech_marketer', name: 'PropTech Marketer' },
  { key: 'proptech_operator', name: 'PropTech Operator' },
  { key: 'proptech_product_manager', name: 'PropTech Product Manager' },
  { key: 'proptech_researcher', name: 'PropTech Researcher' },
  { key: 'proptech_sales_lead', name: 'PropTech Sales Lead' },
  { key: 'proptech_scientist', name: 'PropTech Scientist' },
  { key: 'proptech_specialist', name: 'PropTech Specialist' },
  { key: 'qa_engineer', name: 'QA Engineer' },
  { key: 'quantitative_analyst', name: 'Quantitative Analyst' },
  { key: 'real_estate_analyst', name: 'Real Estate Analyst' },
  { key: 'real_estate_architect', name: 'Real Estate Architect' },
  { key: 'real_estate_consultant', name: 'Real Estate Consultant' },
  { key: 'real_estate_designer', name: 'Real Estate Designer' },
  { key: 'real_estate_director', name: 'Real Estate Director' },
  { key: 'real_estate_engineer', name: 'Real Estate Engineer' },
  { key: 'real_estate_lead', name: 'Real Estate Lead' },
  { key: 'real_estate_manager', name: 'Real Estate Manager' },
  { key: 'real_estate_marketer', name: 'Real Estate Marketer' },
  { key: 'real_estate_operator', name: 'Real Estate Operator' },
  { key: 'real_estate_product_manager', name: 'Real Estate Product Manager' },
  { key: 'real_estate_researcher', name: 'Real Estate Researcher' },
  { key: 'real_estate_sales_lead', name: 'Real Estate Sales Lead' },
  { key: 'real_estate_scientist', name: 'Real Estate Scientist' },
  { key: 'real_estate_specialist', name: 'Real Estate Specialist' },
  { key: 'recruiter', name: 'Recruiter' },
  { key: 'research_scientist', name: 'Research Scientist' },
  { key: 'retail_analyst', name: 'Retail Analyst' },
  { key: 'retail_architect', name: 'Retail Architect' },
  { key: 'retail_consultant', name: 'Retail Consultant' },
  { key: 'retail_designer', name: 'Retail Designer' },
  { key: 'retail_director', name: 'Retail Director' },
  { key: 'retail_engineer', name: 'Retail Engineer' },
  { key: 'retail_lead', name: 'Retail Lead' },
  { key: 'retail_manager', name: 'Retail Manager' },
  { key: 'retail_marketer', name: 'Retail Marketer' },
  { key: 'retail_operator', name: 'Retail Operator' },
  { key: 'retail_product_manager', name: 'Retail Product Manager' },
  { key: 'retail_researcher', name: 'Retail Researcher' },
  { key: 'retail_sales_lead', name: 'Retail Sales Lead' },
  { key: 'retail_scientist', name: 'Retail Scientist' },
  { key: 'retail_specialist', name: 'Retail Specialist' },
  { key: 'robotics_analyst', name: 'Robotics Analyst' },
  { key: 'robotics_architect', name: 'Robotics Architect' },
  { key: 'robotics_consultant', name: 'Robotics Consultant' },
  { key: 'robotics_designer', name: 'Robotics Designer' },
  { key: 'robotics_director', name: 'Robotics Director' },
  { key: 'robotics_engineer', name: 'Robotics Engineer' },
  { key: 'robotics_lead', name: 'Robotics Lead' },
  { key: 'robotics_manager', name: 'Robotics Manager' },
  { key: 'robotics_marketer', name: 'Robotics Marketer' },
  { key: 'robotics_operator', name: 'Robotics Operator' },
  { key: 'robotics_product_manager', name: 'Robotics Product Manager' },
  { key: 'robotics_researcher', name: 'Robotics Researcher' },
  { key: 'robotics_sales_lead', name: 'Robotics Sales Lead' },
  { key: 'robotics_scientist', name: 'Robotics Scientist' },
  { key: 'robotics_specialist', name: 'Robotics Specialist' },
  { key: 'saas_analyst', name: 'SaaS Analyst' },
  { key: 'saas_architect', name: 'SaaS Architect' },
  { key: 'saas_consultant', name: 'SaaS Consultant' },
  { key: 'saas_designer', name: 'SaaS Designer' },
  { key: 'saas_director', name: 'SaaS Director' },
  { key: 'saas_engineer', name: 'SaaS Engineer' },
  { key: 'saas_lead', name: 'SaaS Lead' },
  { key: 'saas_manager', name: 'SaaS Manager' },
  { key: 'saas_marketer', name: 'SaaS Marketer' },
  { key: 'saas_operator', name: 'SaaS Operator' },
  { key: 'saas_product_manager', name: 'SaaS Product Manager' },
  { key: 'saas_researcher', name: 'SaaS Researcher' },
  { key: 'saas_sales_lead', name: 'SaaS Sales Lead' },
  { key: 'saas_scientist', name: 'SaaS Scientist' },
  { key: 'saas_specialist', name: 'SaaS Specialist' },
  { key: 'sales_engineer', name: 'Sales Engineer' },
  { key: 'sales_manager', name: 'Sales Manager' },
  { key: 'security_analyst', name: 'Security Analyst' },
  { key: 'security_architect', name: 'Security Architect' },
  { key: 'security_consultant', name: 'Security Consultant' },
  { key: 'security_designer', name: 'Security Designer' },
  { key: 'security_director', name: 'Security Director' },
  { key: 'security_engineer', name: 'Security Engineer' },
  { key: 'security_lead', name: 'Security Lead' },
  { key: 'security_manager', name: 'Security Manager' },
  { key: 'security_marketer', name: 'Security Marketer' },
  { key: 'security_operator', name: 'Security Operator' },
  { key: 'security_product_manager', name: 'Security Product Manager' },
  { key: 'security_researcher', name: 'Security Researcher' },
  { key: 'security_sales_lead', name: 'Security Sales Lead' },
  { key: 'security_scientist', name: 'Security Scientist' },
  { key: 'security_specialist', name: 'Security Specialist' },
  { key: 'senior_software_engineer', name: 'Senior Software Engineer' },
  { key: 'site_reliability_engineer', name: 'Site Reliability Engineer' },
  { key: 'social_analyst', name: 'Social Analyst' },
  { key: 'social_architect', name: 'Social Architect' },
  { key: 'social_consultant', name: 'Social Consultant' },
  { key: 'social_designer', name: 'Social Designer' },
  { key: 'social_director', name: 'Social Director' },
  { key: 'social_engineer', name: 'Social Engineer' },
  { key: 'social_lead', name: 'Social Lead' },
  { key: 'social_manager', name: 'Social Manager' },
  { key: 'social_marketer', name: 'Social Marketer' },
  { key: 'social_operator', name: 'Social Operator' },
  { key: 'social_product_manager', name: 'Social Product Manager' },
  { key: 'social_researcher', name: 'Social Researcher' },
  { key: 'social_sales_lead', name: 'Social Sales Lead' },
  { key: 'social_scientist', name: 'Social Scientist' },
  { key: 'social_specialist', name: 'Social Specialist' },
  { key: 'software_engineer', name: 'Software Engineer' },
  { key: 'solution_architect', name: 'Solution Architect' },
  { key: 'space_analyst', name: 'Space Analyst' },
  { key: 'space_architect', name: 'Space Architect' },
  { key: 'space_consultant', name: 'Space Consultant' },
  { key: 'space_designer', name: 'Space Designer' },
  { key: 'space_director', name: 'Space Director' },
  { key: 'space_engineer', name: 'Space Engineer' },
  { key: 'space_lead', name: 'Space Lead' },
  { key: 'space_manager', name: 'Space Manager' },
  { key: 'space_marketer', name: 'Space Marketer' },
  { key: 'space_operator', name: 'Space Operator' },
  { key: 'space_product_manager', name: 'Space Product Manager' },
  { key: 'space_researcher', name: 'Space Researcher' },
  { key: 'space_sales_lead', name: 'Space Sales Lead' },
  { key: 'space_scientist', name: 'Space Scientist' },
  { key: 'space_specialist', name: 'Space Specialist' },
  { key: 'sports_analyst', name: 'Sports Analyst' },
  { key: 'sports_architect', name: 'Sports Architect' },
  { key: 'sports_consultant', name: 'Sports Consultant' },
  { key: 'sports_designer', name: 'Sports Designer' },
  { key: 'sports_director', name: 'Sports Director' },
  { key: 'sports_engineer', name: 'Sports Engineer' },
  { key: 'sports_lead', name: 'Sports Lead' },
  { key: 'sports_manager', name: 'Sports Manager' },
  { key: 'sports_marketer', name: 'Sports Marketer' },
  { key: 'sports_operator', name: 'Sports Operator' },
  { key: 'sports_product_manager', name: 'Sports Product Manager' },
  { key: 'sports_researcher', name: 'Sports Researcher' },
  { key: 'sports_sales_lead', name: 'Sports Sales Lead' },
  { key: 'sports_scientist', name: 'Sports Scientist' },
  { key: 'sports_specialist', name: 'Sports Specialist' },
  { key: 'strategy_manager', name: 'Strategy Manager' },
  { key: 'talent_partner', name: 'Talent Partner' },
  { key: 'teacher', name: 'Teacher' },
  { key: 'technical_writer', name: 'Technical Writer' },
  { key: 'telecom_analyst', name: 'Telecom Analyst' },
  { key: 'telecom_architect', name: 'Telecom Architect' },
  { key: 'telecom_consultant', name: 'Telecom Consultant' },
  { key: 'telecom_designer', name: 'Telecom Designer' },
  { key: 'telecom_director', name: 'Telecom Director' },
  { key: 'telecom_engineer', name: 'Telecom Engineer' },
  { key: 'telecom_lead', name: 'Telecom Lead' },
  { key: 'telecom_manager', name: 'Telecom Manager' },
  { key: 'telecom_marketer', name: 'Telecom Marketer' },
  { key: 'telecom_operator', name: 'Telecom Operator' },
  { key: 'telecom_product_manager', name: 'Telecom Product Manager' },
  { key: 'telecom_researcher', name: 'Telecom Researcher' },
  { key: 'telecom_sales_lead', name: 'Telecom Sales Lead' },
  { key: 'telecom_scientist', name: 'Telecom Scientist' },
  { key: 'telecom_specialist', name: 'Telecom Specialist' },
  { key: 'travel_analyst', name: 'Travel Analyst' },
  { key: 'travel_architect', name: 'Travel Architect' },
  { key: 'travel_consultant', name: 'Travel Consultant' },
  { key: 'travel_designer', name: 'Travel Designer' },
  { key: 'travel_director', name: 'Travel Director' },
  { key: 'travel_engineer', name: 'Travel Engineer' },
  { key: 'travel_lead', name: 'Travel Lead' },
  { key: 'travel_manager', name: 'Travel Manager' },
  { key: 'travel_marketer', name: 'Travel Marketer' },
  { key: 'travel_operator', name: 'Travel Operator' },
  { key: 'travel_product_manager', name: 'Travel Product Manager' },
  { key: 'travel_researcher', name: 'Travel Researcher' },
  { key: 'travel_sales_lead', name: 'Travel Sales Lead' },
  { key: 'travel_scientist', name: 'Travel Scientist' },
  { key: 'travel_specialist', name: 'Travel Specialist' },
  { key: 'ux_designer', name: 'UX Designer' },
  { key: 'ux_researcher', name: 'UX Researcher' },
  { key: 'venture_analyst', name: 'Venture Analyst' },
  { key: 'venture_architect', name: 'Venture Architect' },
  { key: 'venture_consultant', name: 'Venture Consultant' },
  { key: 'venture_designer', name: 'Venture Designer' },
  { key: 'venture_director', name: 'Venture Director' },
  { key: 'venture_engineer', name: 'Venture Engineer' },
  { key: 'venture_lead', name: 'Venture Lead' },
  { key: 'venture_manager', name: 'Venture Manager' },
  { key: 'venture_marketer', name: 'Venture Marketer' },
  { key: 'venture_operator', name: 'Venture Operator' },
  { key: 'venture_product_manager', name: 'Venture Product Manager' },
  { key: 'venture_researcher', name: 'Venture Researcher' },
  { key: 'venture_sales_lead', name: 'Venture Sales Lead' },
  { key: 'venture_scientist', name: 'Venture Scientist' },
  { key: 'venture_specialist', name: 'Venture Specialist' },
  { key: 'web_developer', name: 'Web Developer' },
  { key: 'web3_analyst', name: 'Web3 Analyst' },
  { key: 'web3_architect', name: 'Web3 Architect' },
  { key: 'web3_consultant', name: 'Web3 Consultant' },
  { key: 'web3_designer', name: 'Web3 Designer' },
  { key: 'web3_director', name: 'Web3 Director' },
  { key: 'web3_engineer', name: 'Web3 Engineer' },
  { key: 'web3_lead', name: 'Web3 Lead' },
  { key: 'web3_manager', name: 'Web3 Manager' },
  { key: 'web3_marketer', name: 'Web3 Marketer' },
  { key: 'web3_operator', name: 'Web3 Operator' },
  { key: 'web3_product_manager', name: 'Web3 Product Manager' },
  { key: 'web3_researcher', name: 'Web3 Researcher' },
  { key: 'web3_sales_lead', name: 'Web3 Sales Lead' },
  { key: 'web3_scientist', name: 'Web3 Scientist' },
  { key: 'web3_specialist', name: 'Web3 Specialist' },
  { key: 'writer', name: 'Writer' },
  { key: 'product_manager', name: 'Product manager' },
  { key: 'researcher', name: 'Researcher' },
  { key: 'student', name: 'Student' },
  { key: 'vc_partner', name: 'VC partner' },
  { key: 'occupation_other', name: 'Other' },
]
